Repository Normation/rudder-agent, pull requests merged in 2020-05, with the labels that each got.

#298 Fixes #17281: Add doc about return codes to agent man page
  share/commands/agent-run
Labels: qa: Can't merge

#300 Fixes #17424: Fail password confirmation in BCrypt lead to an user with empty password in file
  share/commands/server-create-user
Labels: Ready for merge, qa: Can't merge

#302 Fixes #17561: rudder agent stop displays the list of service event when quiet is required
  share/commands/agent-check
  share/lib/common.sh
Labels: Ready for merge

#303 Fixes #17567: First inventory fails when installing root server
  share/commands/agent-check
  share/commands/agent-health
  share/commands/agent-reset
  share/commands/agent-run
  share/commands/agent-update
  share/commands/remote-run
  share/commands/server-reload-techniques
Labels: Ready for merge, qa: Can't merge
