Repository Normation/rudder-agent, pull requests merged in 2020-10, with the labels that each got.

#324 Fixes #18348: After a factory reset agents can no longer download their policies from the new server they are managed by
  share/commands/agent-factory-reset
Labels: qa: Can't merge

#325 Fixes #18356: Add a command to reset trust
  share/commands/agent-server-keys-reset
Labels: qa: Can't merge

#321 Fixes #18174: commands from error message are launched due to backticks
  share/commands/agent-inventory
Labels: Ready for merge, qa: Can't merge

#327 Fixes #18430: server-reset-keys should call a reset
  share/commands/agent-server-keys-reset
Labels: Ready for merge

#328 Fixes #18432: Parent breaks manual check
  share/commands/agent-check
Labels: Ready for merge
